### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by Eric-Chen-L** [ZikunZhou/GTELT#1]
Hi zikun:
When will you plan to release the code? Looking forward to the GTELT.

**Comment by ZikunZhou** [comment]
Hi Eric, thanks for your attention to our work. Our group is still working on organizing the source codes. You could refer to the codes of STARK and Deformable DETR.

**Comment by ZikunZhou** [comment]
> Hi zikun: When will you plan to release the code? Looking forward to the GTELT.

Hi Eric, thanks for your attention to our work. Our group is still working on organizing the source codes. You could refer to the codes of STARK and Deformable DETR.

**Comment by Eric-Chen-L** [comment]
Thanks for your reply. Hope your work comes out soon.
