### ISSUE TITLE
关于当待跟踪目标出现在两个局部跟踪中间位置时如何确定跟踪器的问题？

### ISSUE THREAD

**Issue by JayHeYang** [ZikunZhou/GTELT#2]
你好，最近我阅读了你们的论文，看完之后有一点儿疑问，即当目标出现在两个或者多个局部跟踪器的中间位置时该如何确定下一帧将由哪个局部跟踪器进行跟踪呢？是通过每次并行预测后选择最高置信度对应的跟踪器，然后把其它的跟踪器结果抑制掉？还是说将每次并行预测的结果都保留并通过TCA模块传播到下一帧，然后每帧的跟踪结果仍然是选择最高置信度对应跟踪器的预测输出呢？ 期待你们的回答，万分感谢:wink: 。

**Comment by ZikunZhou** [comment]
tca只会传递激活的那个局部跟踪器预测的结果



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月21日 10:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [ZikunZhou/GTELT] 关于当待跟踪目标出现在两个局部跟踪中间位置时如何确定跟踪器的问题？ (Issue #2) |

你好，最近我阅读了你们的论文，看完之后有一点儿疑问，即当目标出现在两个或者多个局部跟踪器的中间位置时该如何确定下一帧将由哪个局部跟踪器进行跟踪呢？是通过每次并行预测后选择最高置信度对应的跟踪器，然后把其它的跟踪器结果抑制掉？还是说将每次并行预测的结果都保留并通过TCA模块传播到下一帧，然后每帧的跟踪结果仍然是选择最高置信度对应跟踪器的预测输出？

**Comment by ZikunZhou** [comment]
每一帧具体选择哪个局部跟踪器，是根据置信度来决定的。

**Comment by JayHeYang** [comment]
好的，明白啦，O(∩_∩)O感谢。

**Comment by JayHeYang** [comment]
好的，明白啦，O(∩_∩)O感谢。

**Comment by ZikunZhou** [comment]
根据分类置信度选择



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月21日 10:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [ZikunZhou/GTELT] 关于当待跟踪目标出现在两个局部跟踪中间位置时如何确定跟踪器的问题？ (Issue #2) |

你好，最近我阅读了你们的论文，看完之后有一点儿疑问，即当目标出现在两个或者多个局部跟踪器的中间位置时该如何确定下一帧将由哪个局部跟踪器进行跟踪呢？是通过每次并行预测后选择最高置信度对应的跟踪器，然后把其它的跟踪器结果抑制掉？还是说将每次并行预测的结果都保留并通过TCA模块传播到下一帧，然后每帧的跟踪结果仍然是选择最高置信度对应跟踪器的预测输出？
